parameters:
    creonit.security.user_provider.class: Creonit\UserBundle\Security\UserProvider
    creonit.security.oauth_user_provider.class: Creonit\UserBundle\Security\OAuthUserProvider


services:
    creonit.user.admin.module:
        class: Creonit\UserBundle\Admin\UserModule
        tags: [{name: creonit_admin.module}]

    creonit.security.user_provider:
        class: %creonit.security.user_provider.class%
        arguments: ["@=service(parameter('creonit_user.authorization'))"]

    creonit.security.oauth_user_provider:
        class: %creonit.security.oauth_user_provider.class%
        arguments: ["@=service(parameter('creonit_user.authorization'))"]